### ISSUE TITLE
Love ur work

### ISSUE THREAD

**Issue by Wongcheukwai** [jayelm/lsl#1]
Hi,

I really appreciate your work at NIPS. And how is the update for the code of bird experiments?

And btw, can you tell me the GPU requirement(memory usage) for these two experiments and corresponding running time ?

**Comment by jayelm** [comment]
Code should be around in early January! I've already DMed @Wongcheukwai but if anyone else is in a hurry and needs a messy version of the codebase, DM me.

**Comment by jayelm** [comment]
For GPU requirements: I don't exactly recall memory usage but all tests were done with a single Titan-XP-ish GPU w/ 12GB memory. Memory usage for Shapeworld is lower than Birds.

The ShapeWorld experiments can be run quite fast, in 30-40 minutes on a GPU (the L3 models are a bit slower).

The Birds experiments take a bit longer (2.5-3h for Meta/ML2, ~5h for L3)
