### ISSUE TITLE
Is it possible to generate more data for shapeworld?

### ISSUE THREAD

**Issue by hlml** [jayelm/lsl#11]
Hi, I was wondering if it's possible to generate more training data for the shapeworld task? If so, would you be able to offer some guidance on how to go about doing that? Also, was there a rationale for capping the number of training examples at 9000?

Thanks!
Hattie

**Comment by jayelm** [comment]
Yup, this is possible by using Alex Kuhnle's original shapeworld repository, specifically this commit:

https://github.com/AlexKuhnle/ShapeWorld/tree/82b3c3a106a5d5f6d8afe98c34b301e3ed696865

and the following files (these are the original authors, Jacob Andreas'):

https://gist.github.com/jayelm/d4047ad9b1f77fed2de40627141577b9
https://gist.github.com/jayelm/8b7c2d9539c021c304b13325ae2f903a

I believe `spatial_jda.py` needs to be placed in the folder `shapeworld/datasets/agreement/` and `generate.py` replaces the original generate in the root dir.

re: 9000, we just kept the same number used by Jacob in his original L3 paper.

**Comment by jayelm** [comment]
gonna close this but lmk if you need more help!

**Comment by hlml** [comment]
perfect, thanks so much!
