### ISSUE TITLE
Question about shapeworld dataset

### ISSUE THREAD

**Issue by JACKHAHA363** [jayelm/lsl#2]
Impressive about the tidiness of the codebase! Some questions about the shapeworld dataset

1. The link under `shapesworld/README.md` seems to be not responding

2. Does the dataset contain the captions?

3. Are the captions generated in the same way described by Andreas 2018?

Thanks!

**Comment by jayelm** [comment]
Hi!

1. Did you mean Jacob Andreas' link? He hosted those files, so you might want to raise an issue in his github repo (see https://github.com/jacobandreas/l3/blob/master/data/README.txt)
2. Yes, it does
3. Yes, it's created with the same data generating process, we just make 4x as many. Jacob wrote some code to work with an older version of Alex Kuhnle's shapeworld repository. I'm not sure these files are available in his repo so lmk if you want them and I can email them to you.

**Comment by JACKHAHA363** [comment]
For `1`: I was refering to the link of `http://nlp.stanford.edu/data/muj/shapeworld_4k.tar.gz`

For `3`: Yes, that will be super helpful! My email is `luyuchen.paul@gmail.com`. Thanks for the info!

**Comment by jayelm** [comment]
Hmm, `1` seems to work for me - are you sure it doesn't immediately kick off a download? Does e.g. `wget` not work?
`3`: emailed you

**Comment by JACKHAHA363** [comment]
Yea for `1` wget works. Thanks for the info. I will close the issue now since I have all the information.
