### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hughperkins** [jayelm/lsl#3]
Hi. Awesome paper :) Question: what license is the code available under? (eg, MIT license, https://github.com/git/git-scm.com/blob/master/MIT-LICENSE.txt , would be awesome please :) ).

**Comment by jayelm** [comment]
Hi Hugh - licenses are different for each separate codebase (as the birds codebase is extended from a different repository). So shapeworld is MIT, birds is cc attribution noncommercial. Hope that helps!

**Comment by hughperkins** [comment]
oooo... right. Good point. Thanks! :)
