### ISSUE TITLE
Running shapeworld/run_l3.sh results in error

### ISSUE THREAD

**Issue by hlml** [jayelm/lsl#6]
Hi, thanks for the cool work and the open sourced code! 

I find that when I try to run shapeworld/run_l3.sh, I get the following error:

`RuntimeError: normal_ expects std > 0.0, but found std=0`

Should the setting use a non-zero noise parameter?

**Comment by jayelm** [comment]
Can you give me the full traceback? (Where does this error occur)

**Comment by hlml** [comment]
Sure!

Running `./run_l3.sh`

`/home/hattie/ilenv/lib/python3.7/site-packages/torch/optim/adam.py:48: UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error; see github.com/pytorch/pytorch/issues/40967 for more information
  super(Adam, self).__init__(params, defaults)
  0%|                                                                                                                                                                                                    | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "lsl/train.py", line 668, in <module>
    train_loss = train(epoch)
  File "lsl/train.py", line 391, in train
    train_dataset.sample_train(args.batch_size)
  File "/home/hattie/lsl/shapeworld/lsl/datasets.py", line 394, in sample_train
    self.__getitem__(index)
  File "/home/hattie/lsl/shapeworld/lsl/datasets.py", line 611, in __getitem__
    clamp=not self.precomputed_features)
  File "/home/hattie/lsl/shapeworld/lsl/datasets.py", line 480, in add_noise
    clamp=clamp)
  File "/home/hattie/lsl/shapeworld/lsl/datasets.py", line 494, in _add_noise
    0, self.noise)
RuntimeError: normal_ expects std > 0.0, but found std=0`

(edit: I described another error here but I figured out that it was a mistake on my end. the previous error still occurs)

**Comment by jayelm** [comment]
Which version of pytorch are you using? On torch `1.4.0` the command runs fine.

**Comment by jayelm** [comment]
Otherwise, could you try the `no_noise` branch that I just pushed? I removed a lot of the noise code (which isn't used in any of the expts anyways). If that works ok let me know and I can merge to main. Thanks!

**Comment by jayelm** [comment]
I'll close this for now but feel free to reopen!

**Comment by hlml** [comment]
Sorry for the late reply, the no_noise branch had one issue with `pack_padded_sequence` for me but otherwise works, so I create a pull request (https://github.com/jayelm/lsl/pull/8)

P.S. my pytorch version is 1.7.0

**Comment by jayelm** [comment]
thanks! I'll merge into main
